version: '3.8'

services:

  users:
    container_name: users
    build:
      context: ./users
      dockerfile: Dockerfile-prod
    volumes:
      - './users:/usr/src/app'
    expose:
      - '5000'
    environment:
      - APP_SETTINGS=project.config.ProductionConfig
      - DATABASE_URL=postgresql://postgres:postgres@users-db:5432/users_dev
      - DATABASE_TEST_URL=postgresql://postgres:postgres@users-db:5432/users_test
    depends_on:
      - users-db
    links:
      - users-db

  users-db:
    container_name: users-db
    build:
      context: ./users/project/db
      dockerfile: Dockerfile
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  nginx:
    container_name: nginx
    build: ./nginx
    restart: always
    ports:
      - "81:80"
    depends_on:
      - users

